language: python
python:
- '2.7'
- '3.5'
install: pip install -r requirements.txt
script:
- pip install -U flake8
- pip install -r requirements.txt
- python setup.py install
- python setup.py test
- flake8 xunit_wrapper
deploy:
  provider: pypi
  user: erasche
  password:
    secure: UlAoPqsL8aVvGqCZbQGBQLs+OM2apweKLBR0o9RaiuF6yIvxubqOXB0VdzOCwkNMv8xigDvjz1QoWxxl6vIj13/aqeKD026X5ybNVbW+RaL8QzOJWwEpa3OphpGbM3lfCyZwHzamy+sY3Hhsrc7C+IHUuoZGGF1FX+feXb9n4csQmrIenU3X3S7jNbNRz/D831kr04CwROmJEqdZwjCp7cmq6kzrw3MhOcCPa/K4eI4sgvYt3HqeXr8TYtAkq7VYD+ljExBqs9nfORQbo3Df/PtKF0qKrHw2QaZ7goLKrwPI5xkSXoWO0U7D8Tb35lHhWnxXAZSajFfUCu/M6HTTZAhTwt9eMOOhSnXFD+tHzi+yi1hqQk5sPSv/0jKWyclxDydXIpkr3TEG5+4bcR8G3m9GU2Quvl+hJ3NCNpd69OyBQ4C7dIEKiT1kCecSyizgBaxEJ02PBiZwGymP8rMrxlASesfJd3MYIOAfkrMaPNwgGJGlm1fCNXVCFhMm3VP8AYrRZ4miD3SLjobIYTopaLX7rBf0NuADilj6nlRpOG0+kWuWU9ZaxI3kchU9eKScDqCV1wYU3tNMC7fzBPWPCDrH127LqJUW91IG7hXe09t8AVqffVWf8XWlwCCo7Gm3QLavUBm3pArhz6+HzjFxn/PRL6SRz87NoAe1e2VeYzY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: TAMU-CPT/xunit-python-decorator
